### ISSUE TITLE
Rename modes | Suggestion

### ISSUE THREAD

**Issue by mucke5** [RomanistHere/PopUpOFF#12]
Moderate > Hard mode on this site
Minimal > Easy mode on this site
Strict > I  JUST WANT TO READ!
---
https://github.com/RomanistHere/PopUpOFF#tutorial---since-111

**Comment by RomanistHere** [comment]
Thank you. Sound nice. I'll think about it.

Will keep this issue open. Let's collect some good ideas:)

**Comment by clarkb22086** [comment]
- "Hard mode on this site" ==> **Aggressive Mode**
- "Easy mode on this site" ==> **Relaxed Mode** _(Alternative: **Tolerant Mode**)_
- "I JUST WANT TO READ!" ==> **Extreme Mode** _(Alternative: **Severe Mode**)_

**Comment by makethingsbetter** [comment]
was it really moderate / minimal / strict ?

 dont remember


when you reload, it doesnt remember the settings for 'I JUST WANT TO READ!' but it does for 'hard / easy'

and you cant switch between all 3 to test without reloading (you have to reload for 'I JUST WANT TO READ!')

naming is hard, i dunno

maybe 'hard = clean, no sticky / easy = leaves navigation, less sticky /    'I JUST WANT TO READ! (i like this phrasing but i dont really know what it does relative to 'hard', or how it's different from 'hard' hahahahahah)

gif/image examples that are linked to from the extension would be a good idea actually

**Comment by makethingsbetter** [comment]
fun with naming

agreesive > burn
moderate > balanced
dormant > Off
