### ISSUE TITLE
A feature request

### ISSUE THREAD

**Issue by mozkan007** [RomanistHere/PopUpOFF#14]
Hi, I tried the extension and I want to give a suggestion for the extension. There are 3 mode on the extension and as I understand, we have to choose one of them for each new website we visit and I think that it can be a bit tiring for users. In order to prevent this situation maybe you can add an option for each mode that "enable for all website".Thus we do not have to choose a mod for websites which we visited or we will visit. Thanks a lot.

**Comment by RomanistHere** [comment]
Hello, thanks for your request.

We do need automatic mode for every website from start. That's my current big task, it's in the work right now - and I hope we will enjoy it together very soon:)
