### ISSUE TITLE
hey this is one of the best things i've ever seen on the web ⭐

### ISSUE THREAD

**Issue by makethingsbetter** [RomanistHere/PopUpOFF#16]
if i was a billionaire, would hire you for everything hahahaha😂

im stunned just like you probably are at how in the web nobody else in the global society had made something like this to hide the insane clutter on the web - until you did, congrats!!

i guess a fair amount of them are too busy creating clutter but that's how it always has been in history and things slowly progress over time

i guess there are a few things that do hide 'elements' like ublock origin but they dont make it easy like this extension does - this extension does it simply, and that's what makes it so good

like a user says in chrome review, 

> One button simple click and the page I was having issues with cleared immediately. Very impressed.

---

one of the biggest problems with the web is that navigation is on top. navigation should be on the side

the first thing that is helpful for us to see is the content - navigation is not the content we went to the page/site for - this is 1 of the things this extension helps clean up

to make the web better overall, 1 option in the future is to work at google/chrome. you're have a much bigger effect on the web

only 5 years of xp and a site like this! wow
this site is so clean, polish, and interesting that it's one of the few things that actually inspired me to learn to code one day... there isnt really any exceptionally good resources out there and i've seen most everything, it's a big learning curve

---

typically have js off, so dont know how it is with js on for all sites

i think after auto-hide it's pretty much perfect

other extensions that makes the web better:

- block google results 
https://chrome.google.com/webstore/search/block%20google%20results%20-seo%20-adblocker?_feature=free&_feature=5stars&_category=extensions
- auto-deletes duplicates 
https://chrome.google.com/webstore/detail/chrome-tab-tools/aknanahjikhcdjljhojbndnhfiknfali
- youtube ratings (needs to show % instead of bar) 
https://chrome.google.com/webstore/detail/thumbnail-rating-bar-for/cmlddjbnoehmihdmfhaacemlpgfbpoeb
- block youtube channels
https://chrome.google.com/webstore/detail/blocktube/bbeaicapbccfllodepmimpkgecanonai?hl=en-US
- shows visited links on sites that dont
https://chrome.google.com/webstore/detail/link-control/dibehcgiapedhoehgpinmkdmahlheekc
- better scrolling (can hold middle click + scroll)
https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj
- how to delete acc (designed well also)
https://chrome.google.com/webstore/detail/just-delete-me/hfpofkfbabpbbmchmiekfnlcgaedbgcf
- shows link upon hover (delay for showing link is too slow, needs to be more instant)
https://chrome.google.com/webstore/detail/linktips/eihlofapoahdelmmdphpobogokfmdmbl

a bunch of other things that make different things better

**Comment by RomanistHere** [comment]
Thanks a lot :)

There was a wrong guy in linkedin. I don't know how it happened :) I fixed the link now, thank you again:)
I both studied and got my experience in Belarus and now am looking for something new.
When you are ready to learn JS, give me a call, I'll point you to the most adequate way to start:)

About websites, linkedin is a sort of website, I'd prefer no one use my extension on (I actually do). There are a bunch of them, like youtube, facebook, etc. I think of my extension in terms of news portals, blogs - usual dwellings of the popups.

YouTube PLAS is going to be redesigned and launched again after I finish with Automode developments. 
About my language - it's 100% me all the time. Content at the links you provided - I wrote it more than a year ago and haven't updated much. I would really love to master English and I'm on my way to:)

Yeah, these are good examples. I will definitely have a look. Now plans are to release PopUpOFF 2.0 and redesign Stylify and YouTube PLAS. Create landing pages for it and start. It just takes some time, especially when you have a job.

I am very pleased, if you have something else on mind, don't hesitate to contact me. Have a great day!

**Comment by makethingsbetter** [comment]
sure what do you think is the #1 source (youtube, site, etc, anything) to learn js for anyone that knows nothing about it? ill give it a try and see

on twitter you said you're thinking about 1 + 9
in chrome, you can change minimal font size so that takes care of 1
you can also turn off 9 so it's also not a problem

have you found any best sources for learning english btw? if so, i wanna see how good they are, and how well they do it

**Comment by RomanistHere** [comment]
> sure what do you think is best source (youtube, site, etc, anything) to learn js for anyone that knows nothing about it? ill give it a try and see

Problem with JS is that you want to start with HTML/CSS first. You could learn only JS but it would be harder. If we are talking about front-end (web-sites, applications, extensions) - we're using JS to make something we're not able to do with HTML/CSS (Entry level). So it makes perfect sense to me to start with learning HTML and CSS. It's easy enough, you need only a browser and notepad (I recommend Sublime) to start working and you are going to see the results of what you're doing immediately. There are also a lot of services to write HTML/CSS online, so you basically need only a browser.

So you need services to guide you through HTML/CSS world by-doing. It would be something like this:
- https://www.learn-html.org/
- https://ilovecoding.org/courses/htmlcss2

I can't guarantee it's the best ones, but you certainly need something like this.

After you get some practice with it, you can google [JavaScript event listeners](https://www.w3schools.com/js/js_htmldom_eventlistener.asp) - w3schools is the best place for learning basics of JS. Examples and explanations are great and you can try everything covered in the topic online. Start learning JS with adding event listeners. For example, change the color of the button when you click it. After you write some examples - you can dive in what is function and data types in JS. Don't hesitate to google anything about JS - it's the most popular language in the world, there are no questions of entry level you would not find the answer on stackoverflow.com - or, again, contact me :)

> you can also turn off 9 so it's also not a problem

You can only turn it everywhere, and for some websites, like email ones - you would probably like to have notification options enabled. I'm going to check if we can improve that experience. But right now I have something else in my mind.

> have you found any best sources for learning english btw? if so, i wanna see how good they are

I'm more like a self-learner here: Jack London, Ray Bradbury, George Orwell - are your friends. "Want to master something? Learn from the best man" - is my motto:)

**Comment by makethingsbetter** [comment]
**auto-hide**

this tool was good cos when you want something hidden you can selectively ctrl x

i thought auto-hide was gonna be a good idea but i was wrong
* i suggested it in the past (somewhere? maybe email)
* and after testing it wasnt a good idea

this shows how important it is when techies say to 'move fast, break things'

auto-hide universally hides everything, and so appropriately termed, 'aggresive' 
* popoff has 5 options currently, even moderate: gentle is too aggressive for some sites

for example it removes this helpful extension https://chrome.google.com/webstore/detail/smart-toc/lifgeihcfpkmmlfjbailfpfhbahhibba

i didnt realise how big of a problem auto-hide would be cos, well, it popoff was by default off in the past
but auto-hide made me notice it wasnt a good idea

there's 5 options currently, and having to change it every time there's a button that doesnt work is painful cos of how the UI settings is

im not sure right now whats a good default setting, still testing
maybe Off + ctrl x is the best setting like the was before the update/change

selectively hiding is better cos sites are so varied


---

for noitifcations,
you can selectively allow + block notifications chrome://settings/content/notifications

**Comment by makethingsbetter** [comment]
**cultural languages**

i was gonna make a longterm goal to learn some of the popular foreign languages but couldnt find any good learning sources for basics

i think the best easiest thing is to live in a nation that mostly speaks that langauge, so that's what ill do in longterm

for english, for basics, i dont know if there's anything good that someone has made  i'd recommend for basics

the #1 thing about good commucnaition is **clear** + concise

**for clarity + conciseness**, i dont think fictional writers are a good source for anyone, i think literature/fictional writers are the worst source cos they nuances and particulars, and specific ways they use words that are commonplace in society - that makes things lack clarity 

for english, higher than basics, and for clarity + conciseness, i think a good source would be harvard coginitive science professor steve pinker's book:
* https://www.amazon.com/Sense-Style-Thinking-Persons-Writing/dp/0143127799
* or can just google a pdf of it: http://xidian-usa.org/wp-content/uploads/2019/07/The-Sense-of-Style.pdf

https://www.youtube.com/results?search_query=steven+pinker+sense+of+style&sp=CAMSAhgC

im not sure what or if there's any other good sources

good communciation is about being **clear** + concise

so nonfiction is always gonna be better than > fictional writing

**Comment by makethingsbetter** [comment]
**css / code learning**

not easy

https://ilovecoding.org/courses/htmlcss2 is good, but it's not really that good

i need **visuals**, i need to see what the code does

gonna see if there's any good youtubes or udemy

**Comment by RomanistHere** [comment]
> selectively hiding is better cos sites are so varied

Yeah, I guess, I am still thinking of the ways it could be resolved

> so non-fiction is always gonna be better than > fictional writing

It's true, at this point. But let's think... Popular fictional writers have become popular not only because their minds can create something original and interesting, but because they are also available to express themselves in the way a lot of people would be interested in. So do not very many non-fiction writers (I used to like reading Brian Greene and Stephen Hawking though). I don't say we don't need to read, I myself do plan to read "Garner's Modern English Usage", 
Grammatically Correct: The Essential Guide to Spelling, Style, Usage, Grammar, and Punctuation" - there are just different goals in these books for me.

> not easy
> i need visuals, i need to see what the code does

CSS and HTML can hardly be described as programming, it's just a list of properties you will need to remember. And they are visual by themselves. once you connect  your HTML and CSS magic begins... 
I created something for you: https://codepen.io/romanist1/pen/yLaVPgp - have a look, I added a few html blocks and added some CSS to make it different. All the CSS is intuitive so you can try to change it without even reading what it does. Probably it's going to fascinate you :)
