### ISSUE TITLE
'instructions' -> 'how to use'

### ISSUE THREAD

**Issue by makethingsbetter** [RomanistHere/PopUpOFF#17]
saw this on the twitter

'instructions' -> 'how to use'

'how to use' is:
1. friendlier
2. less formal, more casual
3. gets more users (not that that's the primary goal hahaha)
3. more ppl like
4. more fun

also less letters
8 lettters vs 12 letters
also less space/bits in total xD

---

presets is a genius idea but seems better for a bigger app/tool/software
but is typically hard to do cos there's usually multiple use cases / combinations of settings so not a simple thing to do for many softwares (or really anything else in life)

---

default of auto-hide is pickable via settings i assume - picking 'hard'/clean/no sticky/no clutter

yea i agree 'easy' should be default upon install

- maybe 'easy' / 'moderate'  to -> 'simple'
- and 'agreesive' to -> 'clean' or 'polished' or something nicer
- dont like word aggressive dont think majority of ppl would either 

---

not really any other comemnts just taht there's many many many many other thinigs in life the web and the world that needs to be made better

should release auto-hide so it can be tested whoever has it installed, and later  iterate etc

**Comment by RomanistHere** [comment]
I like "how to use" - will try :)
