### ISSUE TITLE
UX Issues

### ISSUE THREAD

**Issue by JakeQZ** [RomanistHere/PopUpOFF#22]
Great plugin.  I'd thought of implenting something like this via a GreaseMonkey script, because websites are getting too annoying these days in their (ab)use of JavaScript, and I was getting tired of manually removing the pop-ups via the Inspector.  (I don't want to accept all of their cookies, but neither do I want to spend time manually unselecting all but the required ones.  Neither do I want to agree to Google's latest TOS update, because, apparently, I don't need to and can simply remove it from the page.)

Having installed it, it's easy to forget that I have.  But when making an online purchase, I think it blocked the confirmation 'pop-up' ('pop-in'?) that my order was confirmed.  (I sat watching a spinning circle until I got notification of my order confirmation email.)

So maybe there needs to be a clear indication that some action has been taken by the plugin, with the opportunity to revert that specific action?

Also, changing the setting from 'moderate' to 'off' (or any other change) seems to cause the page to reload.  In the case of an online purchase, the specific site actually stated "please don't reload the page", so in that case I would be boxed into a corner.  Presumably the DOM elements added by a specific site's JS are (or at least can be) hidden with `display: none` and re-revealed by user selection, so there's no need for page reload?  (The `overflow` setting for `body` or `html` is somewhat separate?)

Probably multiple issues here.  Happy to try and help out if I find time...

**Comment by RomanistHere** [comment]
Thank you:)

I'm aware of the issues with confirmation popups, and still is in fixing it. You gave me few thoughts, I hope it will be fixed in the next update. 

Sorry for the inconvenience.
