### ISSUE TITLE
Option to add/remove PopUpOff entry from right click context menu

### ISSUE THREAD

**Issue by xypha** [RomanistHere/PopUpOFF#23]
An option to add/remove PopUpOff entry from right click context menu.

PopUpOff icon pinned next to the address bar gives me sufficient control over how the extension works. I don't need it in the context menu (plus it looks un-aesthetic!). Alternatively, you may consider removing the tag line - "popup and overlay blocker")

![Untitled](https://user-images.githubusercontent.com/12472214/103420575-f4a09980-4bbd-11eb-93cb-195afdef31a1.jpg)

Thank you for making the extension. it's very useful :)
Happy New Year!

**Comment by RomanistHere** [comment]
will be available with the next release later this month
