### ISSUE TITLE
PopUpOFF blocks Roboform password manager

### ISSUE THREAD

**Issue by jdt1** [RomanistHere/PopUpOFF#24]
I'm using the Roboform password manager. When there is a field on the page that it can autofill, it will show a small Roboform icon next to the input field. This icon is, however, blocked by PopUpOFF trying to do the right thing. Is there a way to whitelist this icon? 

Example of a login prompt with the Roboform icon on the right of the username edit field.
![image](https://user-images.githubusercontent.com/8831830/110140716-aafa4800-7dd4-11eb-9cff-8844c8f213ec.png)

Is there a way to get this icon allowlisted? I've tried to "Inspect Element" on the icon, but it seems my browser won't let me. Please let me know if I can provide any further information.

Kind regards,
jdt1

**Comment by RomanistHere** [comment]
I will investigate the issue, thanks for pointing out :)

**Comment by RomanistHere** [comment]
Will be fixed in 2.2: https://github.com/RomanistHere/PopUpOFF/issues/34

**Comment by jdt1** [comment]
Amazing! 👏
