### ISSUE TITLE
The pop ups pause the video, they get removed by this plugin, but the video does not restart playback

### ISSUE THREAD

**Issue by fredddd1** [RomanistHere/PopUpOFF#25]
Like the title says:
- I click on a video, it plays for a second
- Pop ups arrive and they pause the video playback
- This plugin automatically gets rid of the pop ups
- The video still remains in paused state and do not continue playing being interrupted by the pop ups

**Comment by RomanistHere** [comment]
Link to the website where it happens would help a bit :)

**Comment by fredddd1** [comment]
> Link to the website where it happens would help a bit :)

Sorry, I thought this was a YouTube plugin. It is YouTube.

**Comment by RomanistHere** [comment]
Thanks for the information, I'll check if it's possible to fix.
