### ISSUE TITLE
Website whitelist | Suggestion

### ISSUE THREAD

**Issue by Achsion** [RomanistHere/PopUpOFF#27]
**What's on your mind?**

It would be nice to add the possibility to add an url to a whitelist (maybe even with a regex), so that all popups on this site won't be blocked.
An alternative solution would be to set a mode as default mode together with the option to change the mode for different websites.

**Why would I like this feature?**

I encountered a problem when trying to manage access to a github repo where it (rightfully) blocked the popup that appears to add/remove access.

**Comment by RomanistHere** [comment]
Hey, Dormant mode is a whitelist option. To set it up as default for every new website go with next steps:
- right click extensions' icon and go to options for Chromium or "manage extension" and "options" for Firefox
- set Automode as Dormant

Now every new website would be opened whitelisted and you can set Moderate or Aggressive on need.
