### ISSUE TITLE
The extension blocks the Popup Blocker prompt from another extension.

### ISSUE THREAD

**Issue by Grafcube** [RomanistHere/PopUpOFF#28]
**Describe the bug**
May be related to #24.
I use the extension [Popup Blocker (strict)](https://chrome.google.com/webstore/detail/popup-blocker-strict/aefkmifgmaafnojlojpnekbpbmjiiogg) and it shows this prompt when a popup is blocked:
![image](https://user-images.githubusercontent.com/34889224/129537726-23a2f4df-b753-4091-a31f-daa21ec56bf4.png)

The issue is that this extension blocks the prompt. It's not a big deal because I can click the other extension's icon and choose to allow or trust but it is an inconvenience. I prefer to use Aggressive mode but it does not happen for Moderate mode. I don't think Aggressive mode should be blocking other extensions.

**To Reproduce**
1. Install the popup blocker extension.
2. Go to any site that opens a new tab.

**Expected behaviour**
The prompt from the extension should be shown.

**Actual behaviour**
Prompt is blocked in Aggressive mode.

**PC**
 - OS: Pop!_OS 21.04
 - Browser: Vivaldi
 - Version: 4.1.2369.18 stable (64-bit)

**Additional context**
I realise that this might be by design for Aggressive mode. It seems like a bug since it's not content from the webpage but from another extension.

Unrelated: This extension has made the internet so much less painful. I just cannot go back to browsing without it. I love it.

**Comment by RomanistHere** [comment]
Thanks for the warm words. I will investigate this problem, however, I think there is no possibility to detect whether web page was changed by it's own rules or from external extension on your PC. That's why it blocks it now.

Moderate mode is less strict, so it allowed the popup.

**Comment by RomanistHere** [comment]
Will be fixed in 2.2: https://github.com/RomanistHere/PopUpOFF/issues/34
