### ISSUE TITLE
Way to submit feedback / broken sites?

### ISSUE THREAD

**Issue by wulph111** [RomanistHere/PopUpOFF#30]
Hello, is there a framework for submitting sites that don't work on "aggressive" for example https://www.yummly.com/recipe/Thin-Mint-Ice-Cream-No-Churn-Ice-Cream--2135494?prm-v1#directions seems to bypass your algorithms
![Screen Shot 2022-04-07 at 7 51 40 PM](https://user-images.githubusercontent.com/22044501/162337449-7b360ed3-1c74-43a5-86f3-517d63c5b4d6.png)

**Comment by RomanistHere** [comment]
Hi. Yeah, you could list them them there when find. I will add later possibility to report it from the extensions itself.

**Comment by RomanistHere** [comment]
This: https://popupoff.org/submit-issue

**Comment by RomanistHere** [comment]
will make a better UX with this feature: https://github.com/RomanistHere/PopUpOFF/issues/35
