### ISSUE TITLE
PopUpOFF - Sorry, we can't get the plugin details - Edge

### ISSUE THREAD

**Issue by sil71sil** [RomanistHere/PopUpOFF#31]
Hello, I am a lady from Argentina and I have this problem: I have been using for a while - 'PopUpOFF - Blocker of
popups and overlays' - in my browser extensions (Edge) and suddenly it doesn't show up anymore.

I look for it and it just isn't there. When trying to download again (last time it was ok, activated and working perfectly) it shows that it is already installed in the browser.

I am using latest version of Microsoft Edge. Last Edge update: around 3pm Oct-23-2022. After this latest update, the icon disappeared from the bar. Also, it was no longer displayed among the installed extensions.

I swear I haven't uninstalled that, it's a great tool and very useful. After several attempts to reinstall, an error message is displayed: ''Sorry, we can't get the plugin details'' .

Maybe I did something wrong without realizing it?
Please help me to fix this problem.

Thank you very much in advance.
English is not my first language, sorry for the mistakes.

![PopUp1](https://user-images.githubusercontent.com/106161247/197420056-d27bc802-bfb3-42f5-b74a-ab341167c361.jpg)
![PopUp2](https://user-images.githubusercontent.com/106161247/197420060-4c2edc7e-d5f4-468c-8e26-36345bad34dc.jpg)
![PopUp3](https://user-images.githubusercontent.com/106161247/197420061-b86e6f03-2ee4-4077-b789-43445e30fc2e.jpg)
![PopUp4](https://user-images.githubusercontent.com/106161247/197420063-306ca0b9-1a08-4f1d-a9c6-4b538f568cd2.jpg)
![PopUp5](https://user-images.githubusercontent.com/106161247/197420064-eac09b7f-8c58-4b08-a1c3-b4f2eedc7fda.jpg)

**Comment by RomanistHere** [comment]
@sil71sil hi, thanks for letting me know, I'll see if I can fix it

**Comment by RomanistHere** [comment]
@sil71sil can you check if it's working now? From what I see it looks like there was an issue on the Microsoft server side

**Comment by RomanistHere** [comment]
couldn't reproduce the issue. If it bothers you again, feel free to reopen.
