### ISSUE TITLE
Discourse Forum Reply Field gets hidden

### ISSUE THREAD

**Issue by lajawi** [RomanistHere/PopUpOFF#39]
**Describe the bug**
On some websites, parts are being removed which are essential to the website, if PopUpOFF is on (no matter what setting). An example is any community forum made with [Discourse](https://discourse.org/) (here's a list of [Discourse Forums](https://www.discourse.org/customers)). If you want to reply to a post, PopUpOFF hides the reply popup which is sticky at the bottom.

**To Reproduce**

1. Go to any Forum build with [Discourse](https://www.discourse.org/customers)
2. Click on a post
3. Try to reply with and without PopUpOFF on (you'll need an account on that forum)
4. If PopUpOFF is on, you cannot reply, because the field is hidden because of it

**Expected behavior**
The reply field shouldn't be hidden because it is vital to the function of the forums

**Screenshots**

**PC (please complete the following information):**

- OS: Windows
- Browser Firefox
- Version 116.0.2

**Additional context**

**Comment by RomanistHere** [comment]
@lajawi thanks for letting me know, I'll see into the issue. Meanwhile, could you please record a video (or at least take a screenshot) showcasing the missing parts with PopUpOFF turned off? It would be helpful.

**Comment by RomanistHere** [comment]
Firefox 116.

![image](https://github.com/RomanistHere/PopUpOFF/assets/49812531/8c3dc7cb-48ce-424c-bb14-001b07f64fa6)

Do you run the last version of PopUpOFF? 2.1.3. You can check here: `about:addons`

![image](https://github.com/RomanistHere/PopUpOFF/assets/49812531/ced79d3b-0b9c-4d9b-b17d-4c53bf995b7d)

**Comment by RomanistHere** [comment]
Couldn't reproduce, feel free to open if there is a new info
