### ISSUE TITLE
[Question] What happens with cookie dialogs?

### ISSUE THREAD

**Issue by BlastboomStrice** [RomanistHere/PopUpOFF#41]
I just found this addon and it looks like it saves me so much time! I just have one question:
What happens with the cookie dialoges? Does it simply hide the dialoge without accepting anything? Does it accept all cookies?

Is it like I'm browsing the page without having "yet" accepted/rejected the cookies of the site?

**Comment by RomanistHere** [comment]
According to rules of most eu countries from what I know unless you specifically clicked "I agree" to cookies, you're considered declining them (as if you clicked don't agree, which option some of them don't event have). However I can't promise you legitimacy of these websites, so if you really care about it, just use `uBlock Origin` and `Privacy Badger` together with PopUpOFF - and no website will be able to force cookies on you unless you will want it to.

**Comment by RomanistHere** [comment]
lmk if you have other questions

**Comment by BlastboomStrice** [comment]
Thank you very much!
