### ISSUE TITLE
There is a overlay on https://shop.apotal.de/view/showcart (when you view the cart page) your addon does not unlock

### ISSUE THREAD

**Issue by Dragodraki** [RomanistHere/PopUpOFF#43]
**What's on your mind?**

When shopping on apotal.de (no problems so far) and like to visit cart items (https://shop.apotal.de/view/showcart) you cannot click anything. Only if you clear the cache and fill out the cookie form manually first it works. Seems the addon does not unlock the overlay or apotal.de detects cookie blocker addon and bans one.
Though its not a frequently visited site, can you please help me and find a fix for this nasty method of apotal.de too?

**Comment by RomanistHere** [comment]
@Dragodraki I just checked. They block form elements untill you agree to the policy or whatever. So click extension's icon, set "Turn OFF" option
![image](https://github.com/RomanistHere/PopUpOFF/assets/49812531/3852e9d7-4dff-4fe6-a0aa-3bb5ab6195e1)

Then reload the site and click the red button
![image](https://github.com/RomanistHere/PopUpOFF/assets/49812531/266db76d-5105-4456-a473-278d44284987)

Form will unlock
